import type { ToolInfo, ToolFeature, PricingPlan } from "@/types/tools"

export const tools: ReadonlyArray<ToolInfo> = [
  {
    id: "cursor",
    name: "Cursor",
    nameEn: "Cursor",
    tagline: "AIファーストのコードエディタ",
    description:
      "Anysphere社が開発したVSCodeベースのAIコードエディタ。コード補完、チャット、エージェントモードなどAI機能を統合的に提供し、開発者の生産性を大幅に向上させます。",
    developer: "Anysphere Inc.",
    category: "AI コードエディタ",
    officialUrl: "https://www.cursor.com/",
    docsUrl: "https://docs.cursor.com/",
    accentColor: "cursor-accent",
    supportedOs: ["windows", "macos", "linux"],
    releaseYear: 2023,
    pricingModel: "subscription",
    highlights: [
      "VSCode完全互換 - 拡張機能もそのまま使える",
      "Tab補完・インラインエディット・チャット・Agentモード搭載",
      "マルチモデル対応（Claude Opus 4.6、Sonnet 4.5、GPT-5.3、Composer など）",
    ],
  },
  {
    id: "claude-code",
    name: "Claude Code",
    nameEn: "Claude Code",
    tagline: "マルチプラットフォーム対応AIコーディングエージェント",
    description:
      "Anthropicが開発したエージェンティックコーディングツール。CLI・VSCode拡張・Web版・JetBrains・モバイルなどマルチプラットフォームで動作し、ファイル操作、コマンド実行、Git操作を自律的に実行。Chrome拡張やExcel連携、Coworkデスクトップエージェントなど広範なClaudeエコシステムとも連携します。",
    developer: "Anthropic",
    category: "AI コーディングエージェント",
    officialUrl: "https://code.claude.com/docs/en/quickstart",
    docsUrl: "https://code.claude.com/docs/en/quickstart",
    accentColor: "claude-accent",
    supportedOs: ["windows", "macos", "linux", "web"],
    releaseYear: 2025,
    pricingModel: "usage-based",
    highlights: [
      "マルチプラットフォーム - CLI・VSCode・Web・JetBrains・モバイルで利用可能",
      "エージェント型 - ファイル読み書き・コマンド実行を自律的に遂行",
      "Claudeエコシステム連携 - Chrome拡張・Excel・Cowork・Agent Teams",
    ],
  },
  {
    id: "manus",
    name: "Manus AI",
    nameEn: "Manus AI",
    tagline: "汎用AIエージェント",
    description:
      "Monica.imが開発した汎用AIエージェント。ブラウザ操作、コード実行、データ分析、リサーチなどをクラウドサンドボックス内で自律的に実行し、非エンジニアでも高度なタスクを自動化できます。",
    developer: "Monica.im",
    category: "汎用 AI エージェント",
    officialUrl: "https://manus.im",
    docsUrl: "https://manus.im",
    accentColor: "manus-accent",
    supportedOs: ["web"],
    releaseYear: 2025,
    pricingModel: "credit-based",
    highlights: [
      "ブラウザ操作でWeb情報を自動収集・分析",
      "コーディング不要 - 自然言語だけでタスクを自動化",
      "リサーチからレポート作成まで一気通貫",
    ],
  },
] as const

export function getToolById(id: string): ToolInfo | undefined {
  return tools.find((tool) => tool.id === id)
}

export const cursorFeatures: ReadonlyArray<ToolFeature> = [
  {
    id: "cursor-tab",
    toolId: "cursor",
    name: "Tab 補完（Cursor Tab）",
    description: "AIがリアルタイムで次のコードを予測・提案。単行から複数行まで、コンテキストを理解した高精度な補完。",
    icon: "Keyboard",
    category: "code-completion",
  },
  {
    id: "cursor-cmd-k",
    toolId: "cursor",
    name: "Cmd+K インラインエディット",
    description: "選択したコードに自然言語で指示を出し、その場でAIが編集。リファクタリングやエラー修正に最適。",
    icon: "Pencil",
    category: "code-editing",
  },
  {
    id: "cursor-chat",
    toolId: "cursor",
    name: "AI チャット",
    description: "サイドパネルでAIと対話。@シンボルでファイルやコードベースを参照し、プロジェクト全体を理解した回答を取得。",
    icon: "MessageSquare",
    category: "chat",
  },
  {
    id: "cursor-composer",
    toolId: "cursor",
    name: "Composer",
    description: "複数ファイルにまたがる大規模なコード変更を一括実行。新規ファイル作成やプロジェクト構造の変更も可能。",
    icon: "Layers",
    category: "agent",
  },
  {
    id: "cursor-agent",
    toolId: "cursor",
    name: "Agent モード",
    description: "AIが自律的にファイルの読み書き、ターミナル操作を実行。エラーの自動修正も行う最も強力なモード。",
    icon: "Bot",
    category: "agent",
  },
  {
    id: "cursor-context",
    toolId: "cursor",
    name: "コンテキスト管理（@シンボル）",
    description: "@file、@folder、@codebase などでAIに参照先を明示。プロジェクト全体のセマンティック検索にも対応。",
    icon: "Search",
    category: "context-management",
  },
]

export const claudeCodeFeatures: ReadonlyArray<ToolFeature> = [
  {
    id: "cc-agentic",
    toolId: "claude-code",
    name: "エージェンティックコーディング",
    description: "ファイルの読み書き、コマンド実行、コードベース検索を自律的に実行。指示一つでタスクを完了まで導く。",
    icon: "Bot",
    category: "agent",
  },
  {
    id: "cc-multi-platform",
    toolId: "claude-code",
    name: "マルチプラットフォーム対応",
    description: "CLI・VSCode拡張・Web版・JetBrains・モバイルなど、あらゆる環境から同じAIエージェントを利用可能。",
    icon: "Monitor",
    category: "agent",
  },
  {
    id: "cc-claude-md",
    toolId: "claude-code",
    name: "CLAUDE.md 設定",
    description: "プロジェクト固有の規約やスタイルをMarkdownで定義。AIが常にプロジェクトルールに従ったコードを生成。",
    icon: "FileText",
    category: "customization",
  },
  {
    id: "cc-mcp",
    toolId: "claude-code",
    name: "MCP（Model Context Protocol）",
    description: "外部サービス（Supabase、Vercel、Playwright等）と連携するプロトコル。プラグインで機能を大幅に拡張。",
    icon: "Plug",
    category: "customization",
  },
  {
    id: "cc-chrome",
    toolId: "claude-code",
    name: "Claude in Chrome（ブラウザ拡張）",
    description: "Chrome上でWebサイトを自然言語で自動操作。ワークフロー録画・マルチタブ管理・スケジュール実行に対応。",
    icon: "Chrome",
    category: "browser-control",
  },
  {
    id: "cc-excel",
    toolId: "claude-code",
    name: "Claude in Excel（スプレッドシート連携）",
    description: "Excel内で数式作成・データ分析・エラー修正・ピボットテーブル操作を自然言語で実行。財務モデル構築にも対応。",
    icon: "Table2",
    category: "data-analysis",
  },
  {
    id: "cc-cowork",
    toolId: "claude-code",
    name: "Claude Cowork（デスクトップエージェント）",
    description: "Claude Desktopでローカルファイルの操作や複雑なタスクを自律実行。結果を指示して離席、完成品を受け取る。",
    icon: "Laptop",
    category: "agent",
  },
  {
    id: "cc-agent-teams",
    toolId: "claude-code",
    name: "Agent Teams（マルチエージェント）",
    description: "複数のClaudeエージェントがチームとして並列協調作業。レビュー・デバッグ・開発を同時に実行。",
    icon: "Network",
    category: "collaboration",
  },
]

export const manusFeatures: ReadonlyArray<ToolFeature> = [
  {
    id: "manus-agent",
    toolId: "manus",
    name: "自律エージェント",
    description: "タスクを自動的にサブタスクに分解し、ToDoリスト形式で進捗を可視化しながら順次実行。",
    icon: "ListTodo",
    category: "agent",
  },
  {
    id: "manus-browser",
    toolId: "manus",
    name: "ブラウザ制御",
    description: "仮想ブラウザをリアルタイムで操作し、Web情報の収集・フォーム入力・スクリーンショット取得を自動化。",
    icon: "Globe",
    category: "browser-control",
  },
  {
    id: "manus-code",
    toolId: "manus",
    name: "コード生成・実行",
    description: "クラウドサンドボックス内でPython、JavaScript等のコードを生成・実行。データ分析やプロトタイプ作成に。",
    icon: "Code",
    category: "code-editing",
  },
  {
    id: "manus-files",
    toolId: "manus",
    name: "ファイル操作",
    description: "PDF・Excel・画像などのファイルをアップロード・処理・生成。データの変換や可視化も自動実行。",
    icon: "FileDown",
    category: "file-operations",
  },
  {
    id: "manus-planning",
    toolId: "manus",
    name: "マルチステップ計画",
    description: "複雑なタスクを段階的な実行計画に分解。エラー発生時は自動でリトライや代替手段を試行。",
    icon: "Map",
    category: "agent",
  },
  {
    id: "manus-multimodal",
    toolId: "manus",
    name: "マルチモーダル対応",
    description: "画像認識・OCR・グラフ生成に対応。スクリーンショットを用いたUI解析やデータの可視化が可能。",
    icon: "Image",
    category: "data-analysis",
  },
]

export const cursorPricing: ReadonlyArray<PricingPlan> = [
  {
    toolId: "cursor",
    name: "Free（Hobby）",
    type: "free",
    price: { monthly: 0, annual: null, currency: "USD" },
    features: [
      { name: "Premium リクエスト", value: "50回/月（低速）", highlight: false },
      { name: "Tab 補完", value: "2,000回/月", highlight: false },
      { name: "プライバシーモード", value: true, highlight: false },
    ],
    recommended: false,
    ctaText: "無料で始める",
    ctaUrl: "https://www.cursor.com/",
  },
  {
    toolId: "cursor",
    name: "Pro",
    type: "pro",
    price: { monthly: 20, annual: 192, currency: "USD" },
    features: [
      { name: "Premium リクエスト", value: "500回/月", highlight: true },
      { name: "Tab 補完", value: "無制限", highlight: true },
      { name: "Slow リクエスト", value: "無制限", highlight: false },
      { name: "プライバシーモード", value: true, highlight: false },
    ],
    recommended: true,
    ctaText: "Pro にアップグレード",
    ctaUrl: "https://www.cursor.com/pricing",
  },
  {
    toolId: "cursor",
    name: "Business",
    type: "business",
    price: { monthly: 40, annual: 384, currency: "USD" },
    features: [
      { name: "Premium リクエスト", value: "500回/月", highlight: false },
      { name: "Tab 補完", value: "無制限", highlight: false },
      { name: "Slow リクエスト", value: "無制限", highlight: false },
      { name: "プライバシーモード", value: "組織全体で強制可能", highlight: true },
      { name: "チーム管理", value: "管理ダッシュボード", highlight: true },
      { name: "SSO/SAML", value: true, highlight: true },
    ],
    recommended: false,
    ctaText: "Business を検討",
    ctaUrl: "https://www.cursor.com/pricing",
  },
]

export const claudeCodePricing: ReadonlyArray<PricingPlan> = [
  {
    toolId: "claude-code",
    name: "API 従量課金",
    type: "pro",
    price: { monthly: null, annual: null, currency: "USD", note: "トークン消費に応じた従量課金" },
    features: [
      { name: "Sonnet 4.5", value: "入力 $3 / 出力 $15（100万トークン）", highlight: true },
      { name: "Opus 4.6", value: "入力 $5 / 出力 $25（100万トークン）", highlight: false },
      { name: "Haiku 4.5", value: "入力 $0.80 / 出力 $4（100万トークン）", highlight: false },
      { name: "プロンプトキャッシュ", value: "コスト削減", highlight: false },
    ],
    recommended: false,
    ctaText: "API キーを取得",
    ctaUrl: "https://console.anthropic.com/",
  },
  {
    toolId: "claude-code",
    name: "Claude Pro",
    type: "pro",
    price: { monthly: 20, annual: null, currency: "USD" },
    features: [
      { name: "基本的な Claude Code 利用", value: true, highlight: false },
      { name: "使用量", value: "標準", highlight: false },
      { name: "APIキー不要", value: "OAuth 認証", highlight: true },
    ],
    recommended: false,
    ctaText: "Pro を始める",
    ctaUrl: "https://claude.ai/",
  },
  {
    toolId: "claude-code",
    name: "Claude Max",
    type: "business",
    price: { monthly: 100, annual: null, currency: "USD", note: "$200/月プランもあり" },
    features: [
      { name: "使用量", value: "Pro の5倍〜20倍", highlight: true },
      { name: "APIキー不要", value: "OAuth 認証", highlight: false },
      { name: "プロフェッショナル向け", value: true, highlight: true },
    ],
    recommended: true,
    ctaText: "Max を始める",
    ctaUrl: "https://claude.ai/",
  },
]

export const manusPricing: ReadonlyArray<PricingPlan> = [
  {
    toolId: "manus",
    name: "Free",
    type: "free",
    price: { monthly: 0, annual: null, currency: "USD" },
    features: [
      { name: "初回無料クレジット", value: "少量付与", highlight: false },
      { name: "基本機能", value: true, highlight: false },
    ],
    recommended: false,
    ctaText: "無料で試す",
    ctaUrl: "https://manus.im",
  },
  {
    toolId: "manus",
    name: "Plus",
    type: "pro",
    price: { monthly: 39, annual: null, currency: "USD" },
    features: [
      { name: "月間クレジット", value: "一定量", highlight: true },
      { name: "全機能利用可能", value: true, highlight: false },
      { name: "個人利用向け", value: true, highlight: false },
    ],
    recommended: true,
    ctaText: "Plus を始める",
    ctaUrl: "https://manus.im",
  },
  {
    toolId: "manus",
    name: "Pro / Team",
    type: "business",
    price: { monthly: null, annual: null, currency: "USD", note: "要問い合わせ" },
    features: [
      { name: "大量クレジット", value: true, highlight: true },
      { name: "ビジネス利用向け", value: true, highlight: true },
      { name: "優先サポート", value: true, highlight: false },
    ],
    recommended: false,
    ctaText: "お問い合わせ",
    ctaUrl: "https://manus.im",
  },
]
